from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('sucesiones_trenes/',views.vista_cargarSucesionTrenes, name= 'vista_cargarSucesionTrenes'),
    path ('home/',views.vista_home, name = 'home'),
    path('cambios_turnos/',views.get_solicitudes_cambios_turnos, name= 'cambios_turnos'),
    path('editarHorario/',views.editar_horario, name='editar_horario'),
    path('configuraciones/',views.vista_configuraciones, name= 'configuraciones'),
    path('cargarInstruccionesOperacionales/',views.vista_cargarIo, name = 'cargarIo'),
    path('solicitudes_gestion_turnos/', views.vista_solicitudes_gestion_turnos, name = "solicitudesGt"),
    path('notificaciones/',views.vista_notificaciones, name="notificaciones"),
    path('precarga/', views.vista_precarga, name="preCarga"),
    path('dashboard/', views.vista_dashboard, name = "vista_dashboard"),
    path('verificacion/', views.vista_verificacion, name = "verificacion"),
    # urls  - > API
    path("api/mis-turnos/", views.get_mis_turnos, name="get_mis_turnos"),
    path('api/sucesion/',views.get_sucesion_cargo,name="get_sucesion_cargo"),
    path('api/actualizar_turno/',views.actualizar_turno, name="actualizar_turno"),
    path('api/consultar_turno/',views.consultar_turno, name="consultar_turno"),
    path('api/traer_horarios/',views.traer_horarios, name = "traer_horarios"),
    path('api/eliminar_horario/',views.eliminar_horario, name="eliminar_horario"),
    path('api/insertar_horario/', views.insertar_horario, name="insertar_horario"),
    path('api/buscar_cambio_turno/', views.buscar_cambio_turno, name="buscar_cambio_turno"),
    path('api/solicitar_cambio_turno/', views.solicitar_cambio_turno, name= "solicitar_cambio_turno"),
    path('api/aprobar_solicitudes_cambios_turnos/', views.aprobar_solicitudes_cambios_turnos, name = "aprobar_solicitudes_cambios_turnos"),
    path('api/desaprobar_solicitudes_cambios_turnos/', views.desaprobar_solicitudes_cambios, name = "desaprobar_solicitudes_cambios_turnos"),
    path('api/cargarComunicados/',views.cargar_Io, name="cargarComunicados"),
    path('api/solicitudesgt/',views.solicitud_gt, name = "solicitudesgt"),
    path('api/actualizar_parametros/',views.actualizar_parametros, name="actualizar_parametros"),
    path('api/get_archivos_solicitudesgt/',views.get_archivos_solicitudesgt, name="get_archivosgt"),
    path('api/aprobarSolicitudesGt/',views.gestionarSolicitudeGt, name="gestionarSolicitudeGt"),
    path('api/insertar_estado/', views.insertar_estado, name= "insertar_estado"),
    path('api/get_comunicados/',views.get_comunicados, name= "get_comunicados"),
    path('api/getTodosComunicados/', views.getTodosComunicados , name = "getTodosComunicados"),
    path('api/confirmacionLectura/', views.confirmacionLectura, name = "confirmacionLectura"),
    path('api/get_datos_filtro_sucesion/',views.get_datos_filtro_sucesion, name = "datos_filtro_sucesion"),
    path('api/cabeceras_turnos/', views.cabeceras_turnos, name = "cabeceras_turnos"),
    path('api/mis_solicitudes_cambios_turnos/', views.mis_solicitudes_cambios_turnos, name = "mis_solicitudes_cambios_turnos"),
    path('api/insertarRespuesta/', views.insertarRespuesta, name = "insertarRespuesta"),
    path('api/getRespuesta/', views.getRespuesta, name = "getRespuesta"),
    path('api/descargarInformeGt/', views.descargarInformeGt, name = "descargarInformeGt"),
    path('api/misSolicitudesGT/', views.misSolicitudesGT, name= 'misSolicitudesGT'),
    path('api/getSolicitudesCambiosTurnos/',views.getSolicitudesCambiosTurnos, name="getSolicitudesCambiosTurnos"),
    path('api/cancelarSolicitudGt/', views.cancelarSolicitudGt, name="cancelarSolicitudGt"),
    path('api/misSolicitudesCambiosTurnos/', views.misSolicitudesCambiosTurnos, name = "misSolicitudesCambiosTurnos"),

    ]