# Generated by Django 5.2.2 on 2025-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio_turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_emp_uno', models.CharField(max_length=20)),
                ('codigo_emp_dos', models.CharField(max_length=20)),
                ('codigo_turn_uno', models.CharField(max_length=20)),
                ('codigo_turn_dos', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('Nombres', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_turno', models.CharField(max_length=20)),
                ('fecha_turno', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('lugar_inicio', models.CharField(max_length=20)),
                ('lugar_final', models.CharField(max_length=20)),
                ('particularidades', models.TextField(max_length=200)),
            ],
        ),
    ]
