# Generated by Django 5.2.2 on 2025-06-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0002_sucesion_delete_cambio_turnos_delete_empleado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucesion',
        ),
    ]
