# Generated by Django 5.2.2 on 2025-06-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignacion_turnos', '0003_delete_sucesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('estado_inicio', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_fin', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('codigo_horario', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario_carga', models.CharField(max_length=50)),
                ('fecha_carga', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
