# Generated by Django 5.2.2 on 2025-06-10 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucesion',
            name='usuario_carga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100, verbose_name='Nombre del Horario')),
                ('fechavigencia', models.DateField(verbose_name='Fecha de Vigencia')),
                ('fechaimplementacion', models.DateField(verbose_name='Fecha de Implementación')),
                ('version', models.CharField(max_length=50, verbose_name='Versión')),
                ('turno', models.CharField(max_length=100, verbose_name='Nombre del Turno')),
                ('inihora', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('inilugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Inicio')),
                ('inicir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Circuito Inicio')),
                ('deshora', models.TimeField(blank=True, null=True, verbose_name='Hora de Despliegue')),
                ('deslugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Despliegue')),
                ('desrelevo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Relevo Despliegue')),
                ('descir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Circuito Despliegue')),
                ('seghora', models.TimeField(blank=True, null=True, verbose_name='Hora Segmento')),
                ('seglugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Segmento')),
                ('segcir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Circuito Segmento')),
                ('finalhora', models.TimeField(blank=True, null=True, verbose_name='Hora Final')),
                ('finallugar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Final')),
                ('finalrelevo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Relevo Final')),
                ('finbalcir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Circuito Final')),
                ('duracion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duración Turno')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_carga', models.DateField(auto_now_add=True)),
                ('usuario_carga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario de Turno',
                'verbose_name_plural': 'Horarios de Turno',
            },
        ),
    ]
