# Generated by Django 5.2.2 on 2025-06-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0006_sucesion_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucesion',
            name='codigo_horario',
        ),
    ]
