# Generated by Django 5.2.2 on 2025-06-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0007_remove_sucesion_codigo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucesion',
            name='codigo_turno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.CharField(max_length=20, verbose_name='Nombre del Turno'),
        ),
    ]
