# Generated by Django 5.2.2 on 2025-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0009_rename_codigo_turno_sucesion_codigo_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucesion',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
