# Generated by Django 5.2.3 on 2025-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0010_sucesion_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucesion',
            name='codigo_horario',
            field=models.CharField(default='SRM123', max_length=20),
        ),
    ]
