# Generated by Django 5.2.2 on 2025-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0011_alter_sucesion_codigo_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado_Oddo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
    ]
