# Generated by Django 5.2.2 on 2025-06-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0012_empleado_oddo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucesion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_turnos.empleado_oddo'),
        ),
        migrations.AlterField(
            model_name='sucesion',
            name='codigo_horario',
            field=models.CharField(max_length=20),
        ),
    ]
