# Generated by Django 5.2.2 on 2025-06-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0013_sucesion_empleado_alter_sucesion_codigo_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucesion',
            name='cargo',
        ),
    ]
