# Generated by Django 5.2.2 on 2025-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0015_cambios_de_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='estado_cambio_admin',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
    ]
