# Generated by Django 5.2.2 on 2025-06-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0016_cambios_de_turnos_estado_cambio_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucesion',
            name='estado_sucesion',
            field=models.CharField(default='revision', max_length=50),
        ),
    ]
