# Generated by Django 5.2.2 on 2025-07-07 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0017_sucesion_estado_sucesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha_carga',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
