# Generated by Django 5.2.2 on 2025-07-07 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0018_alter_horario_fecha_carga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambios_de_turnos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cambios_de_turnos',
            name='turno_receptor',
        ),
        migrations.RemoveField(
            model_name='cambios_de_turnos',
            name='turno_solicitante',
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='fecha_solicitud_cambio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='turno_receptor_nuevo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='turno_receptor_original',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='turno_solicitante_nuevo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='turno_solicitante_original',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cambios_de_turnos',
            name='estado_cambio_admin',
            field=models.CharField(default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='cambios_de_turnos',
            name='estado_cambio_emp',
            field=models.CharField(default='pendiente', max_length=30),
        ),
    ]
