# Generated by Django 5.2.2 on 2025-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0019_remove_cambios_de_turnos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios_de_turnos',
            name='estado_cambio_emp',
            field=models.CharField(default='disponible', max_length=30),
        ),
    ]
