# Generated by Django 5.2.2 on 2025-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0020_alter_cambios_de_turnos_estado_cambio_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='cargo_receptor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='cargo_solicitante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
