# Generated by Django 5.2.2 on 2025-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0021_cambios_de_turnos_cargo_receptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados_servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_carga', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio_permitida_cambios', models.CharField(max_length=10)),
                ('hora_final_permitida_cambios', models.CharField(max_length=10)),
                ('dia_inicio_permitida_cambios', models.CharField(max_length=20)),
                ('dia_final_permitida_cambios', models.CharField(max_length=20)),
            ],
        ),
    ]
