# Generated by Django 5.2.2 on 2025-07-08 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0022_estados_servicios_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_servicios',
            name='fecha_carga',
            field=models.CharField(default=django.utils.timezone.localdate, max_length=20),
        ),
    ]
