# Generated by Django 5.2.2 on 2025-07-09 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0023_alter_estados_servicios_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados_servicios',
            name='fecha_carga',
            field=models.DateField(default=django.utils.timezone.localdate, max_length=20),
        ),
    ]
