# Generated by Django 5.2.2 on 2025-07-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0024_alter_estados_servicios_fecha_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='dia_final_permitida_cambios',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='dia_inicio_permitida_cambios',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='hora_final_permitida_cambios',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='hora_inicio_permitida_cambios',
            field=models.TimeField(max_length=10),
        ),
    ]
