# Generated by Django 5.2.2 on 2025-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0025_alter_parametros_dia_final_permitida_cambios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='dia_final_permitida_cambios',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='dia_inicio_permitida_cambios',
            field=models.CharField(max_length=20),
        ),
    ]
