# Generated by Django 5.2.2 on 2025-07-14 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0026_alter_parametros_dia_final_permitida_cambios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_cambios_de_turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_solicitante', models.CharField(max_length=10)),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('cargo_solicitante', models.CharField(max_length=50, null=True)),
                ('turno_solicitante_original', models.CharField(max_length=10, null=True)),
                ('turno_solicitante_nuevo', models.CharField(max_length=10, null=True)),
                ('codigo_receptor', models.CharField(max_length=10)),
                ('nombre_receptor', models.CharField(max_length=100)),
                ('cargo_receptor', models.CharField(max_length=50, null=True)),
                ('turno_receptor_original', models.CharField(max_length=10, null=True)),
                ('turno_receptor_nuevo', models.CharField(max_length=10, null=True)),
                ('fecha_solicitud_cambio', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
    ]
