# Generated by Django 5.2.2 on 2025-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0027_solicitud_cambios_de_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucesion',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
