# Generated by Django 5.2.2 on 2025-07-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0028_sucesion_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado_oddo',
            name='formacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='zona',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado_oddo',
            name='estado',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
