# Generated by Django 5.2.2 on 2025-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0029_empleado_oddo_formacion_empleado_oddo_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucesion',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
