# Generated by Django 5.2.2 on 2025-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0030_sucesion_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado_oddo',
            name='zona',
            field=models.BooleanField(default=False),
        ),
    ]
