# Generated by Django 5.2.2 on 2025-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0031_alter_empleado_oddo_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado_oddo',
            name='zona',
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='formacion_receptor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='formacion_solicitante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
