# Generated by Django 5.2.2 on 2025-08-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0032_remove_empleado_oddo_zona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fechaCarga', models.DateField(auto_now_add=True)),
                ('usuarioCarga', models.CharField(max_length=50)),
                ('tipoComunicado', models.CharField(max_length=30)),
                ('fechaVigencia', models.DateField(blank=True, null=True)),
                ('cargoVisualizacion', models.CharField(max_length=50)),
                ('urlArchivo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('tipo_solicitud', models.CharField(max_length=50, null=True)),
                ('fecha_solicitud', models.DateField(null=True)),
                ('fecha_notificacion', models.DateTimeField()),
                ('correo', models.CharField(max_length=50)),
                ('medio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='barrio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='municipio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='zona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parametros',
            name='hora_final_solicitudesgt',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='parametros',
            name='hora_inicio_solicitudesgt',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='ConfirmacionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacionLectura', models.CharField(default='pendiente', max_length=10)),
                ('archivos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_turnos.archivos')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_turnos.empleado_oddo')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes_Gt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=50)),
                ('tipo_solicitud', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('descripcion', models.TextField()),
                ('urlArchivo', models.CharField(max_length=500, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_turnos.empleado_oddo')),
            ],
        ),
    ]
