# Generated by Django 5.2.2 on 2025-08-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0033_archivos_notificaciones_empleado_oddo_barrio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado_oddo',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='empleado_oddo',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleado_oddo',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='empleado_oddo',
            name='zona',
        ),
    ]
