# Generated by Django 5.2.2 on 2025-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0034_remove_empleado_oddo_barrio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucesion',
            name='usuario_carga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
