# Generated by Django 5.2.2 on 2025-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0035_alter_sucesion_usuario_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='usuario_carga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
