# Generated by Django 5.2.2 on 2025-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0036_alter_horario_usuario_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado_oddo',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
