# Generated by Django 5.2.2 on 2025-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0037_alter_empleado_oddo_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='cargoVisualizacion',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='archivos',
            name='urlArchivo',
            field=models.URLField(max_length=2000),
        ),
    ]
