# Generated by Django 5.2.2 on 2025-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0038_alter_archivos_cargovisualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionlectura',
            name='cedula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='confirmacionlectura',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='confirmacionlectura',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
