# Generated by Django 5.2.2 on 2025-08-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0039_confirmacionlectura_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='tipoArchivo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
