# Generated by Django 5.2.2 on 2025-08-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0040_archivos_tipoarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado_oddo',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado_oddo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
