# Generated by Django 5.2.2 on 2025-08-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0041_alter_empleado_oddo_cargo_alter_empleado_oddo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='cargoVisualizacion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cambios_de_turnos',
            name='cargo_receptor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud_cambios_de_turnos',
            name='cargo_receptor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_cambios_de_turnos',
            name='cargo_solicitante',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudes_gt',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucesion',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
