# Generated by Django 5.2.2 on 2025-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0042_alter_archivos_cargovisualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes_gt',
            name='tipoArchivo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
