# Generated by Django 5.2.2 on 2025-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0043_solicitudes_gt_tipoarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado_oddo',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
