# Generated by Django 5.2.2 on 2025-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0044_empleado_oddo_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado_oddo',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
