# Generated by Django 5.2.2 on 2025-08-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0045_alter_empleado_oddo_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado_oddo',
            name='barrio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='municipio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='zona',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
