# Generated by Django 5.2.2 on 2025-09-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0046_empleado_oddo_barrio_empleado_oddo_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='comentarios',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
