# Generated by Django 5.2.2 on 2025-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0047_cambios_de_turnos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='transportable',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cambios_de_turnos',
            name='estado_cambio_emp',
            field=models.CharField(default='pendiente', max_length=30),
        ),
    ]
