# Generated by Django 5.2.2 on 2025-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0048_cambios_de_turnos_terminos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambios_de_turnos',
            name='comentarios',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
