# Generated by Django 5.2.2 on 2025-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0049_alter_cambios_de_turnos_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fechaimplementacion',
            field=models.DateField(null=True, verbose_name='Fecha de Implementación'),
        ),
    ]
