# Generated by Django 5.2.2 on 2025-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0050_alter_horario_fechaimplementacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes_gt',
            name='respuesta',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
