# Generated by Django 5.2.2 on 2025-09-23 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0051_solicitudes_gt_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado_oddo',
            name='foto',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Respuesta_Solicitudes_Gt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(default='Sin respuesta por ahora', max_length=200, null=True)),
                ('fechaRespuesta', models.DateTimeField()),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_turnos.solicitudes_gt')),
            ],
        ),
    ]
