# Generated by Django 5.2.2 on 2025-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0052_empleado_oddo_foto_respuesta_solicitudes_gt'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes_gt',
            name='foto',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
