# Generated by Django 5.2.2 on 2025-09-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0053_solicitudes_gt_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_gt',
            name='respuesta',
            field=models.CharField(default='Sin respuesta aún', max_length=600),
        ),
    ]
