# Generated by Django 5.2.2 on 2025-09-29 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0054_alter_solicitudes_gt_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes_gt',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='solicitudes_gt',
            name='respuestaSolicitudesGt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion_turnos.respuesta_solicitudes_gt'),
        ),
    ]
