# Generated by Django 5.2.2 on 2025-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0055_remove_solicitudes_gt_respuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_solicitudes_gt',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='respuesta_solicitudes_gt',
            name='idSolicitud',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
