# Generated by Django 5.2.2 on 2025-09-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0056_remove_respuesta_solicitudes_gt_solicitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_solicitudes_gt',
            name='idSolicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudes_gt',
            name='respuestaSolicitudesGt',
        ),
        migrations.AddField(
            model_name='respuesta_solicitudes_gt',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='asignacion_turnos.solicitudes_gt'),
        ),
        migrations.AlterField(
            model_name='respuesta_solicitudes_gt',
            name='fechaRespuesta',
            field=models.DateTimeField(null=True),
        ),
    ]
