# Generated by Django 5.2.2 on 2025-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0057_remove_respuesta_solicitudes_gt_idsolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_solicitudes_gt',
            name='idSolicitud',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
