# Generated by Django 5.2.2 on 2025-09-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0058_respuesta_solicitudes_gt_idsolicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_solicitudes_gt',
            name='idSolicitud',
        ),
    ]
