# Generated by Django 5.2.2 on 2025-10-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0059_remove_respuesta_solicitudes_gt_idsolicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambios_de_turnos',
            old_name='transportable',
            new_name='zonaReceptor',
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='zonaSolicitante',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
