# Generated by Django 5.2.2 on 2025-10-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0060_rename_transportable_cambios_de_turnos_zonareceptor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambios_de_turnos',
            name='terminos',
        ),
    ]
