# Generated by Django 5.2.2 on 2025-10-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0061_remove_cambios_de_turnos_terminos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='transportable',
            field=models.BooleanField(default=False),
        ),
    ]
