# Generated by Django 5.2.2 on 2025-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0062_cambios_de_turnos_transportable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambios_de_turnos',
            old_name='transportable',
            new_name='transportable_receptor',
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='transportable_solicitante',
            field=models.BooleanField(default=False),
        ),
    ]
