# Generated by Django 5.2.2 on 2025-10-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0063_rename_transportable_cambios_de_turnos_transportable_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado_oddo',
            name='carrera',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='empleado_oddo',
            name='universidad',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
