# Generated by Django 5.2.2 on 2025-10-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0064_empleado_oddo_carrera_empleado_oddo_fechaingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='tipo_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitudes_gt',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='solicitudes_gt',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='solicitudes_gt',
            name='nombre',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleado', to='asignacion_turnos.empleado_oddo'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='solicitudes_Gt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_Gt', to='asignacion_turnos.solicitudes_gt'),
        ),
    ]
