# Generated by Django 5.2.2 on 2025-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0065_remove_notificaciones_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
