# Generated by Django 5.2.2 on 2025-10-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0066_notificaciones_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacionlectura',
            name='fechaLectura',
            field=models.DateField(null=True),
        ),
    ]
