# Generated by Django 5.2.2 on 2025-10-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0067_confirmacionlectura_fechalectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='cedula_receptor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='cedula_solicitante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
