# Generated by Django 5.2.2 on 2025-11-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_turnos', '0068_cambios_de_turnos_cedula_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambios_de_turnos',
            name='horaAprobacion',
            field=models.DateTimeField(null=True),
        ),
    ]
