"""
Django settings for gestion_turnos project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from identity.django import Auth

# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar el archivo .env
load_dotenv(dotenv_path=BASE_DIR / ".env")

# Ahora puedes usar las variables de entorno con os.getenv()
SECRET_KEY = os.getenv("SECRET_KEY", "default-secret-key")
DEBUG = os.getenv("DEBUG", "False") == "True"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-ssu*fg*a4akxu3eo$sscpgy4=tlg8e6$c5!cs0%-&c*iv@8por'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# MUY IMPORTANTE: incluir el esquema (https://)
CSRF_TRUSTED_ORIGINS = [
    "https://gtconduccion.fundacionudea.net",
    # Opcional (si usas subdominios o Azure por detrás):
    "https://*.fundacionudea.net",
    "https://*.azurewebsites.net",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'asignacion_turnos.apps.AsignacionTurnosConfig',
    'rest_framework', 
    'corsheaders',
    'identity',  # Asegúrate de que este es el nombre correcto del paquete
]


TIME_ZONE = 'America/Bogota'
USE_TZ = True

# DRF: formatear salida
REST_FRAMEWORK = {
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M', 
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_turnos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_turnos.wsgi.application'
LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "account/home/"    # Or any other endpoint

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
 #  'default': {
  #     'ENGINE': 'django.db.backends.sqlite3',
   #    'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH = Auth(
os.getenv('CLIENT_ID'),
client_credential=os.getenv('CLIENT_SECRET'),
redirect_uri=os.getenv('REDIRECT_URI'),
#scopes=os.getenv('SCOPE', "").split(),
#scopes= ["User.Read", "GroupMember.Read.All", "Directory.Read.All", "User.Read.All", "User.ReadBasic.All"],
authority=os.getenv('AUTHORITY'),
)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'


LOGOUT_REDIRECT_URL_ALLOWED = True

CORS_ALLOW_ALL_ORIGINS = True

#Configuraciones para el envio de correos electronicos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("USERNAME_GMAIL")
EMAIL_HOST_PASSWORD =  os.getenv("PASSWORD_GMAIL")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
